/* ===== Rope Cut — Shop & IAP System ===== */
(function() {
  'use strict';
  let shopContainer=null;
  let activeTab='upgrades';
  function fmtPrice(p){return '€'+p.toFixed(2);}
  function createShopPanel(){
    if(shopContainer){shopContainer.style.display='block';showTab(activeTab);return;}
    shopContainer=document.createElement('div');shopContainer.id='shop-panel';
    shopContainer.innerHTML=`<div class="shop-overlay"></div><div class="shop-window"><button class="shop-close">&times;</button><h2 class="shop-title">🛒 Shop</h2><div class="shop-balance-bar"><span class="balance-item"><span class="coin-icon">🪙</span> <span id="shop-coins">0</span></span><span class="balance-item"><span class="gem-icon">💎</span> <span id="shop-gems">0</span></span></div><div class="shop-tabs"><button class="shop-tab" data-tab="coins">🪙 Shop</button><button class="shop-tab" data-tab="gems">💎 Gems</button><button class="shop-tab" data-tab="upgrades">⚡ Upgrades</button><button class="shop-tab" data-tab="premium">👑 Premium</button></div><div class="shop-content" id="shop-content"></div></div>`;
    document.body.appendChild(shopContainer);
    shopContainer.querySelector('.shop-close').addEventListener('click',closeShop);
    shopContainer.querySelector('.shop-overlay').addEventListener('click',closeShop);
    shopContainer.querySelectorAll('.shop-tab').forEach(t=>t.addEventListener('click',()=>showTab(t.dataset.tab)));
    showTab('upgrades');updateBalances();
  }
  function closeShop(){if(shopContainer)shopContainer.style.display='none';}
  function showTab(tabId){activeTab=tabId;if(!shopContainer)return;shopContainer.querySelectorAll('.shop-tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===tabId));const c=shopContainer.querySelector('#shop-content');switch(tabId){case'coins':renderCoinShop(c);break;case'gems':renderGemShop(c);break;case'upgrades':renderUpgradeStation(c);break;case'premium':renderPremiumShop(c);break;}updateBalances();}
  function updateBalances(){const c=shopContainer?.querySelector('#shop-coins');const g=shopContainer?.querySelector('#shop-gems');if(c)c.textContent=ProgressionSystem.getCoinBalance();if(g)g.textContent=ProgressionSystem.getGemBalance();}
  function renderCoinShop(container){const cat=ProgressionSystem.getCatalog();const state=ProgressionSystem.getState();let h='<div class="shop-section"><h3>🎨 Themes</h3><div class="shop-grid">';for(const t of cat.themes){const o=state.ownedThemes.includes(t.id);const a=state.activeTheme===t.id;h+=`<div class="shop-item ${o?'owned':''} ${a?'active':''}" data-type="theme" data-id="${t.id}" data-price="${t.price}"><div class="item-preview theme-preview" style="background:linear-gradient(135deg,${t.colors.bg},${t.colors.accent})"></div><div class="item-name">${t.name}</div><div class="item-desc">${t.desc}</div>${o?(a?'<span class="item-status">✓ Active</span>':'<button class="btn-equip">Equip</button>'):`<button class="btn-buy">🪙 ${t.price}</button>`}</div>`;}h+='</div></div><div class="shop-section"><h3>🔪 Blade Skins</h3><div class="shop-grid">';for(const s of cat.bladeSkins){const o=state.ownedBladeSkins.includes(s.id);const a=state.activeBladeSkin===s.id;h+=`<div class="shop-item ${o?'owned':''} ${a?'active':''}" data-type="bladeSkin" data-id="${s.id}" data-price="${s.price}"><div class="item-name">${s.name}</div><div class="item-desc">${s.desc}</div>${o?(a?'<span class="item-status">✓ Active</span>':'<button class="btn-equip">Equip</button>'):`<button class="btn-buy">🪙 ${s.price}</button>`}</div>`;}h+='</div></div><div class="shop-section"><h3>🪢 Rope Styles</h3><div class="shop-grid">';for(const r of cat.ropeStyles){const o=state.ownedRopeStyles.includes(r.id);const a=state.activeRopeStyle===r.id;h+=`<div class="shop-item ${o?'owned':''} ${a?'active':''}" data-type="ropeStyle" data-id="${r.id}" data-price="${r.price}"><div class="item-name">${r.name}</div><div class="item-desc">${r.desc}</div>${o?(a?'<span class="item-status">✓ Active</span>':'<button class="btn-equip">Equip</button>'):`<button class="btn-buy">🪙 ${r.price}</button>`}</div>`;}h+='</div></div><div class="shop-section"><h3>⚡ Power-Ups</h3><div class="shop-grid">';for(const p of cat.powerupPacks){h+=`<div class="shop-item" data-type="powerup" data-id="${p.id}" data-price="${p.price}"><div class="item-name">${p.name}</div><div class="item-desc">${p.desc}</div><button class="btn-buy">🪙 ${p.price}</button></div>`;}h+='</div></div>';container.innerHTML=h;container.querySelectorAll('.btn-buy').forEach(b=>b.addEventListener('click',(e)=>{const i=e.target.closest('.shop-item');handleCoinPurchase(i.dataset.type,i.dataset.id,parseInt(i.dataset.price),i);}));container.querySelectorAll('.btn-equip').forEach(b=>b.addEventListener('click',(e)=>{const i=e.target.closest('.shop-item');handleEquip(i.dataset.type,i.dataset.id);}));}
  function handleCoinPurchase(type,id,price,el){const state=ProgressionSystem.getState();const om={theme:'ownedThemes',bladeSkin:'ownedBladeSkins',ropeStyle:'ownedRopeStyles'};if(om[type]&&state[om[type]].includes(id)){handleEquip(type,id);return;}if(!ProgressionSystem.spendCoins(price)){showNotification('Not enough coins!');return;}const am={theme:'ownedThemes',bladeSkin:'ownedBladeSkins',ropeStyle:'ownedRopeStyles'};const actm={theme:'activeTheme',bladeSkin:'activeBladeSkin',ropeStyle:'activeRopeStyle'};if(am[type]){state[am[type]].push(id);state[actm[type]]=id;ProgressionSystem.save();}else if(type==='powerup'){const pack=ProgressionSystem.getCatalog().powerupPacks.find(p=>p.id===id);if(pack){for(const[k,v]of Object.entries(pack.items)){state.powerups[k]=(state.powerups[k]||0)+v;}ProgressionSystem.save();}}showNotification('Purchased! ✨');showTab('coins');}
  function handleEquip(type,id){const state=ProgressionSystem.getState();const m={theme:{arr:'ownedThemes',key:'activeTheme'},bladeSkin:{arr:'ownedBladeSkins',key:'activeBladeSkin'},ropeStyle:{arr:'ownedRopeStyles',key:'activeRopeStyle'}};const m2=m[type];if(!m2||!state[m2.arr].includes(id))return;state[m2.key]=id;ProgressionSystem.save();showTab('coins');showNotification(`${type} applied! ✅`);}
  function renderGemShop(container){const packs=ProgressionSystem.getGemPacks();let h='<div class="shop-section"><h3>💎 Buy Gems</h3><div class="shop-grid gem-grid">';for(const p of packs){const t=p.gems+p.bonus;h+=`<div class="shop-item gem-pack ${p.popular?'popular':''}" data-id="${p.id}">${p.popular?'<div class="popular-badge">🔥 Best Value</div>':''}<div class="gem-amount">💎 ${t.toLocaleString()}</div>${p.bonus>0?`<div class="gem-bonus">+${p.bonus} bonus</div>`:''}<div class="gem-base">${p.gems.toLocaleString()} gems</div><button class="btn-buy premium-btn">${fmtPrice(p.price)}</button></div>`;}h+='</div></div>';container.innerHTML=h;container.querySelectorAll('.gem-pack .btn-buy').forEach(b=>b.addEventListener('click',()=>{const id=b.closest('.gem-pack').dataset.id;const d=ProgressionSystem.getGemPacks().find(p=>p.id===id);if(!d)return;ProgressionSystem.addGems(d.gems+d.bonus);showNotification(`💎 Purchased ${d.gems+d.bonus} gems!`);updateBalances();}));}
  function renderUpgradeStation(container){const tiers=ProgressionSystem.getUpgradeTiers();const state=ProgressionSystem.getState();const bonuses=ProgressionSystem.getActiveBonuses();let h='<div class="shop-section"><h3>⚡ Upgrade Station</h3><div class="bonus-summary"><span>🔪 Ropes: <strong>${bonuses.ropeCount}</strong></span><span>🕸️ Basket: <strong>+${bonuses.basketSize*10}px</strong></span><span>⭐ Score: <strong>${bonuses.scoreMult}x</strong></span></div><div class="upgrade-balance"><span>🪙 ${state.coins.toLocaleString()}</span><span>💎 ${state.gems}</span></div>';for(const[cat,tier]of Object.entries(tiers)){const cl=state.upgrades[cat]||0;const cd=tier.levels[cl];const nd=tier.levels[cl+1];const mx=cl>=tier.maxLevel;const cost=mx?null:ProgressionSystem.getUpgradeCost(cat,cl);h+=`<div class="upgrade-card" data-cat="${cat}"><div class="upgrade-header"><span class="upgrade-icon">${tier.icon}</span><span class="upgrade-name">${tier.name}</span><span class="upgrade-level">Lv.${cl} → ${cl+1}</span></div><div class="upgrade-bar"><div class="upgrade-fill" style="width:${(cl/tier.maxLevel)*100}%"></div></div><div class="upgrade-dots">`;for(let i=0;i<=tier.maxLevel;i++)h+=`<span class="upgrade-dot ${i<=cl?'filled':''} ${i===cl+1?'next':''}">${i}</span>`;h+=`</div>`;if(cd)h+=`<div class="upgrade-current">Current: <strong>${cd.name}</strong></div>`;if(nd)h+=`<div class="upgrade-next">Next: <strong>${nd.name}</strong></div>`;if(mx)h+=`<div class="upgrade-maxed">⭐ MAX LEVEL ⭐</div>`;else if(cost)h+=`<div class="upgrade-actions"><button class="btn-upgrade coin-upgrade ${state.coins>=cost.coins?'':'disabled'}" data-cat="${cat}" data-currency="coins">🪙 ${cost.coins.toLocaleString()}</button><button class="btn-upgrade gem-upgrade ${state.gems>=cost.gems?'':'disabled'}" data-cat="${cat}" data-currency="gems">💎 ${cost.gems}</button></div>`;h+=`</div>`;}h+='</div>';container.innerHTML=h;container.querySelectorAll('.btn-upgrade:not(.disabled)').forEach(b=>b.addEventListener('click',()=>{const cat=b.closest('.upgrade-card').dataset.cat;const r=ProgressionSystem.upgradeItem(cat,b.dataset.currency==='gems');if(r.success){showNotification(`⬆️ ${cat} upgraded!`);renderUpgradeStation(container);updateBalances();}else showNotification(`Not enough ${b.dataset.currency}!`);}));}
  function renderPremiumShop(container){const premium=ProgressionSystem.getPremiumItems();const state=ProgressionSystem.getState();let h='<div class="shop-section"><h3>👑 Premium Shop</h3><h4>⚔️ Legendary Blades</h4><div class="shop-grid">';for(const s of premium.legendarySkins){const o=!!state.inventory[s.id];h+=`<div class="shop-item premium-item ${o?'owned':''}"><div class="premium-tier">${s.tier}</div><div class="item-name">${s.name}</div><div class="item-desc">${s.desc}</div>${o?'<span class="item-status">✓ Owned</span>':`<button class="btn-buy premium-btn iap-btn" data-id="${s.id}" data-price="${s.price}">${fmtPrice(s.price)}</button>`}</div>`;}h+='</div><h4>📦 Bundles</h4><div class="shop-grid">';for(const b of premium.bundles){const o=!!state.inventory[b.id];h+=`<div class="shop-item premium-item ${o?'owned':''}"><div class="item-name">${b.name}</div><div class="item-desc">${b.desc}</div>${o?'<span class="item-status">✓ Owned</span>':`<button class="btn-buy premium-btn iap-btn" data-id="${b.id}" data-price="${b.price}">${fmtPrice(b.price)}</button>`}</div>`;}h+=`</div><h4>🎫 Subscriptions</h4><div class="shop-grid">`;for(const p of premium.premiumCases){const o=!!state.inventory[p.id];h+=`<div class="shop-item premium-item ${o?'owned':''}"><div class="item-name">${p.name}</div><div class="item-desc">${p.desc}</div>${o?'<span class="item-status">✓ Owned</span>':`<button class="btn-buy premium-btn iap-btn" data-id="${p.id}" data-price="${p.price}">${fmtPrice(p.price)}</button>`}</div>`;}h+=`</div><h4>🚫 Ads</h4><div class="shop-grid"><div class="shop-item premium-item ${state.adFree?'owned':''}"><div class="item-name">${premium.removeAds.name}</div><div class="item-desc">${premium.removeAds.desc}</div>${state.adFree?'<span class="item-status">✓ Purchased</span>':`<button class="btn-buy premium-btn iap-btn" data-id="remove_ads" data-price="${premium.removeAds.price}">${fmtPrice(premium.removeAds.price)}</button>`}</div></div></div>`;container.innerHTML=h;container.querySelectorAll('.iap-btn').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.id;const p=parseFloat(b.dataset.price);if(confirm(`Purchase for ${fmtPrice(p)}?`)){ProgressionSystem.purchasePremiumItem(id);showNotification('✅ Purchased!');renderPremiumShop(container);updateBalances();}}));}
  function showNotification(msg){const el=document.getElementById('notification')||(()=>{const n=document.createElement('div');n.id='notification';document.body.appendChild(n);return n;})();el.textContent=msg;el.className='show';clearTimeout(el._timeout);el._timeout=setTimeout(()=>el.className='',2500);}
  window.ShopUI={open:createShopPanel,close:closeShop,showTab,updateBalances};
})();
